apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: order
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      run: order
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: order
    spec:
      containers:
      - image: docker.io/ewolff/microservice-kubernetes-demo-order:latest
        name: order
        ports:
        - containerPort: 8080
        resources: {}
status: {}
